### ISSUE TITLE
Unwanted scroll to top in Webkit browsers

### ISSUE THREAD

**Issue by ellisonbg** [codemirror/codemirror5#147]
I am attaching an example below that shows the bug.  Here is how to reproduce:
- Open up the page in a Webkit browser (Chrome or Safari).
- Click the area to dynamically insert more code editors.  Keep adding until the container div starts to scroll a bit.
- Scroll down and try to type in one of the code editors that is off the bottom of the div.
- Some of the time, when you click in the code editor, the div will scroll to the top.
- Some of the time, you are able to click in the code editor, but typing causes a scroll jitter.

Some of the factors that seems to influence this behavior.
- The fact that I am using overflow: hidden on the body to make the div rather than the page scroll.
- The fact that I am using the flexible box model and the container div is a vbox.  Removing this makes the problems go away.

**Comment by chriscalo** [comment]
I was experiencing a similar issue when using CSS Grid. For anyone arriving at this later, here's what fixed it for me in case it saves others some time.

I had the following HTML structure. Details omitted for brevity.

```html
<div class="grid">
  <div class="grid-item">
    <div class="container" style="height: 100%; width: 100%;">
      <!-- CodeMirror instance here -->
    </div>
  </div>
</div>
```

Not exactly sure what was the issue, but the fix was pretty simple. I just added `position: absolute` to the parent element of the CodeMirror instance (`<div class="container"/>`):

```html
<div class="grid">
  <div class="grid-item">
    <div class="container" style="position: absolute; height: 100%; width: 100%;">
      <!-- CodeMirror instance here -->
    </div>
  </div>
</div>
```
