### ISSUE TITLE
[extraKeys] numpad

### ISSUE THREAD

**Issue by peterkroon** [codemirror/codemirror5#2101]
Chrome stable w7 32

I'm unable to make key bindings with my numpad.
- Is this intentional?
- If so why?
- Or is there something broken....?

``` javascript

extraKeys {
  "Ctrl-0": function(cm) {
    //keyCode 48 works but 96 doesn't 
  }
}

```

**Comment by tophf** [comment]
Why not add all the numpad keys like `divide`? For example, currently it's not possible to assign `blockComment` command to `Ctrl-Shift-NumpadDivide` (keyCode: 111).

**Comment by marijnh** [comment]
If you have a list of these and their corresponding key codes, I'll happily add them.

**Comment by tophf** [comment]
Found a [list](http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00000520.html) that applies to javascript despite the page title:

name | keyCode
-----|------
NumpadMultiply | 106
NumpadAdd | 107
NumpadEnter | 13
NumpadSubtract | 109
NumpadDecimal | 110
NumpadDivide | 111

Numpad 0-9 should also be added: `for (var i = 0; i < 10; i++) keyNames[i + 96] = "Numpad" + i;`

**Comment by marijnh** [comment]
Since we are already normalizing between numpad and non-numpad keys for the digits and enter (and, looking at the code, apparently also for num-equals and num-minus), I think we should continue that way and just map these to existing similar keys. The weird case is num-multiply, because `*` does not exist as a raw key. Attached patch goes ahead and binds it to `"*"` anyway, so that we have at least some name for it.
