### ISSUE TITLE
Show hint merge json data

### ISSUE THREAD

**Issue by nikmauro** [codemirror/codemirror5#2378]
Hello it possible showhint function to push/merge and a json data list?

**Comment by ExoticObjects** [comment]
Attempting to use the code that djadmin added above `CodeMirror.registerHelper("hint","yourOwnHint",function(cm,options){`

does not work. 

It never gets called unless I set the second argument to 'coffeescript', and then my default coffescript completions don't get called. So THAT's no good...

Here's an actual code sample of what @marijnh said above (found [here](http://stackoverflow.com/a/19269913/869838)):

    var anyWord = CodeMirror.hint.anyword;
    CodeMirror.hint.anyword = function(cm) {

        var inner = anyWord(cm) || {from: cm.getCursor(), to: cm.getCursor(), list: []};
        inner.list.push("codemirror", "docs", "are", "very", "unclear", "on", "this", "topic");
        return inner;
    };

CodeMirror is pretty fantastic, but [this particular section of the documentation](http://codemirror.net/doc/manual.html#addon_show-hint ) is light on code samples and heavy on words that can be interpreted incorrectly.

The following is not too helpful:

> If no hinting function is given, the addon will use CodeMirror.hint.auto, which calls getHelpers with the "hint" type to find applicable hinting functions, and tries them one by one. If that fails, it looks for a "hintWords" helper to fetch a list of completable words for the mode, and uses CodeMirror.hint.fromList to complete from those.

This describes ways to *replace* default completions for a given language. If you add a helper, it will use it, and replace the one used by the language. If you add a 'hint', it will use the first one that succeeds. (In my experience, it will not call all 'hint' helpers). If you add a 'hintWords' helper, it will use that and only that - it will not use your 'hints' and your 'hintWords' together. 

So, to *add* to a language's set of words to autocomplete, you need to do what @marijnh said above. That information doesn't exist anywhere in the documentation, but rather in a single stackoverflow post (and in his comment above, though less clearly). It should be documented, and even better, CodeMirror should make this easier to do, as it's a very common use case.
