### ISSUE TITLE
selecting text, then changing applications, then regaining focus replaces selected text by a single "-"

### ISSUE THREAD

**Issue by williamstein** [codemirror/codemirror5#2703]
This bug is similar to #1730 and #2481, and is serious because it can lead to data loss.

Highlight everything in a sufficiently large codemirror editor instance (e.g., http://codemirror.net/demo/complete.html), focus on another application, then come back, and sometimes the contents of the editor is replaced by a -.

I was able to sometimes see this same problem several times with http://codemirror.net/demo/complete.html, though rarely.
I will keep trying to make this more clearly reproducible.  I'm reporting this mainly in the hopes that it'll be useful to somebody, and perhaps you could better explain the mysterious code in codemirror.js around

```
minimal = hasCopyEvent &&
```
## More details and a workaround...

Sometimes users of SageMathCloud (using Codemirror 4.x) have complained that their entire file was replaced by a dash.  I've never seen this myself, so I didn't understand how it could happen.   It turns out, they copied the contents of a file from Codemirror (via select all) to an external editor, then come back to SageMathCloud, changed tabs in SageMathCloud (which causes a focus event in CodeMirror), and find that their file is replaced by a -.  I never saw this because I do all my editing in CodeMirror.    With SMC, this happens every single time, and is pretty disturbing.   It only happens on Chrome and Safari (at least it doesn't happen on Firefox).   

Since this is a pretty significant problem (the whole file is deleted), as a workaround, I replaced the line in codemirror.js

```
minimal = hasCopyEvent &&
```

by 

```
minimal = false && hasCopyEvent && 
```

Doing this completely stops the problem from happening (not surprisingly, looking at the source code).  Of course this causes another problem, where the sometimes selection vanishes when returning to the browser -- however, that is a much less serious bug.

**Comment by nomennescio** [comment]
I'm experiencing this issue on Win7 with Chrome 59.

When copying text to the clipboard, and pasting, text larger than 1000 bytes will get replaced by a single '-'. In my case it will even get triggered WITHIN the CodeMirror pane, as well as when switching between the pane and an external editor.

Isn't that also what the indicated code seems to do?

`
minimal = hasCopyEvent && (range.to().line - range.from().line > 100 || (selected = cm.getSelection()).length > 1000);
var content = minimal ? "-" : selected || cm.getSelection();
`

So why is that piece of code in in the first place? It seems to be exactly the piece of code that is triggered, just as the original bug reporter mentioned.

The only "workaround" is to copy-paste smaller pieces of text, one by one, until the whole block is copied. That is ridiculous.

**Comment by nomennescio** [comment]
To copy and paste text, I use the CTRL-C and CTRL-V keys after CTRL-A (or selecting text with the mouse).

**Comment by nomennescio** [comment]
I've also found why this bug triggered.
It seems to be due to a Chrome plugin
https://github.com/jswanner/DontFuckWithPaste

Adding the site to the 'exclude URL pattern' list, will not trigger the bug.
It is probably due to assumptions on your part about an expected series of events, which that plugin changes.

**Comment by guiambros** [comment]
+1! The `"-"` behavior was driving me crazy the last few weeks. I thought it was a bug on Jupyter Labs/Notebook, until I realized copy/paste worked fine in Firefox.

In the end the culprit in my case was also [DFWP](https://github.com/jswanner/DontFuckWithPaste), the same Chrome extension mentioned by @nomennescio. Disabling the extension, or adding to the URL exclusion list, solved the issue for me. Details [here](https://github.com/Codewars/codewars.com/issues/1024#issuecomment-314312415).

While the issue is not caused by CodeMirror directly, maybe there's an opportunity to replace the default "-" with a more intuitive message (or maybe a message in console.log?) explaining why the user is seeing it.

**Comment by marijnh** [comment]
DFWP seems to completely disable all copy/cut/paste events. So yeah, if you install an extension that intentionally breaks browser functionality, it shouldn't come as a huge surprise that libraries that rely on that functionality break.

The hack with the dash existed because updating the hidden textarea's value with a large string used to be very expensive, so CodeMirror only did it when the selection is small or the user is about to copy or cut (in which case the browser needed to find it in the focused element).

But modern browsers seem to have much improved that, and since this was a fragile hack that is now, apparently, not that necessary anymore, I've removed it in attached patch.

**Comment by guiambros** [comment]
> _DFWP seems to completely disable all copy/cut/paste events._

Exactly. DFWP disable clipboard events, in order to block sites from nefarious or annoying behaviors -- e.g., forms not allowing you to paste in password confirmation field.

In this case, even with DFWP enabled, the copy & paste still worked with <1000 characters. It was only over this limit that the JS injected by DFWP triggered the hidden textarea hack in CM, resulting in the `"-"`.

Anyway, I agree with the sentiment; you're certainly asking for trouble when you install a Chrome extension that modifies your clipboard behavior -- even if the intent is to restore its original functionality :)

Thanks for the quick patch! Much appreciated.
