### ISSUE TITLE
Paren highlighting in vim mode is a character off

### ISSUE THREAD

**Issue by michaelballantyne** [codemirror/codemirror5#2934]
For example, with the s-expression:

```
(test
  (fresh ()
    test))
```

With the cursor over the final parenthesis in normal mode, the set of parens that is highlighted are those around `(fresh () test)`.

**Comment by ggeise** [comment]
@marijnh I was looking into this and I tracked it down to the way the cursor is shown in Vim's command mode, where it's shown on top of the current character instead of in front of or behind it. Would it be reasonable to set something on matchBracket's config to tell it to match only when the cursor is on a bracket and not after it? Can or should I access its config from vim.js?

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
