### ISSUE TITLE
non-BMP characters in vim mode behave badly

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/codemirror5#5363]
1. https://codemirror.net/demo/vim.html, go to last line and enter insert mode
2. paste 💖
3. esc

expected:
the heart is still there

actual: as you move around the 14th line, the heart renders as two questionmark/replacement characters. this is generally only a visual issue (when you go into insert mode things start working fine). but if you put the (command mode) cursor at the start of the line and double-click the line, then the questionmark/replacement characters persist into insert mode as well.

**Comment by marijnh** [comment]
The problem seems to be that the vim mode blindly moves the cursor back one index position when exiting insert mode, without making sure it is still on a character boundary. The vim mode isn't being supported anymore, but if you want to fix this, the way to go would be to figure out where that cursor motion is happening and making sure that position isn't in the middle of a surrogate pair.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
