### ISSUE TITLE
How to yank into the global register?

### ISSUE THREAD

**Issue by piotryordanov** [codemirror/codemirror5#6341]
Hello,

I have vim mode enabled.
I am trying to yank to the global register by typing `"*y``. But, it doesn't' seem to work.
Any idea why?

Thx!

**Comment by ufsn4aaa8612** [comment]
*y

**Comment by ianhi** [comment]
@piotryordanov I think you essentially mean filling the system clipboard? If so then it is because the yank function was written before there was good browser support for filling the clipboard via javascript. I discussed this more here: https://github.com/codemirror/CodeMirror/issues/3075#issuecomment-612319694 

If you want this then you should either do what I did and patch it in the environment you are using codemirror and/or make a PR to this repo implementing it (I held off from this because my technique does not work in safari yet)

**Comment by benhormann** [comment]
That register isn't implemented.
Reading from the clipboard is the awkward part (since CodeMirror expects a synchronous return value). Firefox support is the still the biggest blocker.

@ianhi Here's a register that works for yank, change, and delete (but not really for `"*p`):
```js
CodeMirror.Vim.defineRegister('*', ((text) => ({
  setText(t) {
    text = t;
    navigator.clipboard.writeText(text)
      .catch(e => {
      console.log('Write to clipboard failed: ' + e);
      alert('Copy to clipboard failed.\nCheck site permission and HTTPS.');
    });
  },
  toString() {
    return text;
  }
}))(''));
```
Firefox: To enable `writeText`, go to about:config and set `dom.events.asyncClipboard.dataTransfer`.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
