### ISSUE TITLE
Vim mapping fails after changing mode

### ISSUE THREAD

**Issue by Archie-2021** [codemirror/codemirror5#6911]
I am trying to get the hang of obsidian vim, but looks like there is a serious problem with it. Whenever key mapping that It causes to exit the normal mode it stops at that step, it work fine of course in gVim. lets say a very simple command like :nmap ii stops after going into the insert mode and don’t put the i after that (same with O o c keys I have tried, but a key sequence like re which stays in ).

tested on Windows 10 and Brave Browser

**Comment by benhormann** [comment]
The problem isn't changing mode, it is because Insert-mode doesn't support mappings like that. You can only trigger actions, not insert characters directly. It relies on keyboard events to insert characters, and recording macro/replay registers. So adding (complete) support for mapping is not trivial.

The somewhat good news is that you can add your own actions using the [Vim API](https://codemirror.net/doc/manual.html#vimapi), which can call the [content API](https://codemirror.net/doc/manual.html#api_content) to change the document. I haven't really tried it, but I suspect it might not work properly with `.` (replay).

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.

**Comment by Archie-2021** [comment]
> 

 to make sure i understood it correctly, you are saying that all vim related reports should go to that repository after this, right?

**Comment by marijnh** [comment]
Yeah — maintenance of that code is no longer done in this project.
