### ISSUE TITLE
Global CodeMirror variable

### ISSUE THREAD

**Issue by priand** [codemirror/codemirror5#736]
I wrapped the codemirror code into a requireJS module but, to get it working, I had to remove the 'var' keyword when defining the global CodeMirror variable. This is because it is now executed inside a function, so the var keyword defines a local variable, instead of a global one.
Not a big deal, but can you make the change on your source code? Or use window.CodeMirror when defining it?

Thanks!

**Comment by djadmin** [comment]
>to let the developer choose RequireJS module names > paths mapping (as it should be).

+1.
@marijnh : The problem comes when we have changed our baseUrl in require Configuration. The add-ons looks for '../../lib/codemirror.js' which comes out to be a different based on different baseUrl.

It would be great if we could have something like this for every addon which supports AMD.
```define(["codemirror"], mod);``` instead of ```define(['../../lib/codemirror']);```.

Thanks
Dheeraj

**Comment by marijnh** [comment]
Use the `packages` configuration option in requirejs to configure your path to CodeMirror, as in [this demo](http://codemirror.net/demo/requirejs.html). I believe that'll help.

**Comment by djadmin** [comment]
+1. Thank you for the help.
