### ISSUE TITLE
Setting for using spaces instead of tabs

### ISSUE THREAD

**Issue by Gozala** [codemirror/codemirror5#988]
I may be missing something but I'm not able to detect a way to configure codemirror such that it would use spaces for indentation when a tabs button is used. Maybe there is a way to do it via custom keys but even so it's common enough case (since all editors have such option) to have a dedicated option for that.

**Comment by JasinYip** [comment]
Try this :)
```
extraKeys:
    'Tab': -> editor.execCommand 'insertSoftTab'
```

**Comment by amrondonp** [comment]
I'm having a little trouble in a use case I want to support. I want to let the users paste their code or upload the code from a file.  I have been thinking that is not very efficient to replace the tabs in the code string whenever it changes. I would like to do this without changing the source code of codemirror. any ideas?

**Comment by marijnh** [comment]
You can use the `beforeChange` event to inspect and modify changes before they are applied.

**Comment by chriscalo** [comment]
In case this is useful for anyone else, my favorite solution: 

```js
extraKeys: {
  Tab: (cm) => cm.execCommand("indentMore"),
  "Shift-Tab": (cm) => cm.execCommand("indentLess"),
},
```

It couldn't be simpler, and it has the following behavior, which I think is 👌:

- If text on one or more lines is selected, all lines get indented (or outdented) with either tabs or spaces according to the `indentWithTabs` boolean option, and the selection range does not change
- If there's no selection, no matter where the cursor is—even in the middle of a word—that line gets indented (or outdented) (because who actually needs to insert tabs anywhere in code except for leading indentation)
- If the cursor is somewhere in the leading whitespace of a line, one more level of indentation is added and the cursor is moved to the end of the new leading whitespace

Now the only thing left to figure out is how to delete 2 spaces at a time instead of just one…

**Comment by danielearwicker** [comment]
Indenting the current line with no selection would probably annoy a lot of people. It’s very common to line up “table-like” declarations by hitting the tab key at end or middle of the line.

**Comment by haoranyu** [comment]
If having the setting:

```javascript
        indentWithTabs    : false,
        smartIndent       : true,
```

Then the following setting might be good for a better experience of using the tab key.

```javascript
extraKeys: {
  Tab: (cm) => {
    if (cm.getMode().name === 'null') {
      cm.execCommand('insertTab');
    } else {
      if (cm.somethingSelected()) {
        cm.execCommand('indentMore');
      } else {
        cm.execCommand('insertSoftTab');
      }
    }
  },
  Backspace: (cm) => {
    if (cm.getSelections().length === 1) {
      let cursorPos = cm.getCursor().ch;
      let indentation = cm.getStateAfter(cm.getCursor().line).indented;
      let indentUnit = cm.options.indentUnit;
      if (cursorPos <= indentation && cursorPos % indentUnit === 0) {
        cm.execCommand('indentLess');
      } else {
        cm.execCommand('delCharBefore');
      }
    }
  },
  'Shift-Tab': (cm) => cm.execCommand('indentLess')
}
```

**Comment by windy** [comment]
> If having the setting:
> 
> ```js
>         indentWithTabs    : false,
>         smartIndent       : true,
> ```
> 
> Then the following setting might be good for a better experience of using the tab key.
> 
> ```js
> extraKeys: {
>   Tab: (cm) => {
>     if (cm.getMode().name === 'null') {
>       cm.execCommand('insertTab');
>     } else {
>       if (cm.somethingSelected()) {
>         cm.execCommand('indentMore');
>       } else {
>         cm.execCommand('insertSoftTab');
>       }
>     }
>   },
>   Backspace: (cm) => {
>     if (!cm.somethingSelected()) {
>       let cursorsPos = cm.listSelections().map((selection) => selection.anchor);
>       let indentUnit = cm.options.indentUnit;
>       let shouldDelChar = false;
>       for (let cursorIndex in cursorsPos) {
>         let cursorPos = cursorsPos[cursorIndex];
>         let indentation = cm.getStateAfter(cursorPos.line).indented;
>         if (!(indentation !== 0 &&
>            cursorPos.ch <= indentation &&
>            cursorPos.ch % indentUnit === 0)) {
>           shouldDelChar = true;
>         }
>       }
>       if (!shouldDelChar) {
>         cm.execCommand('indentLess');
>       } else {
>         cm.execCommand('delCharBefore');
>       }
>     } else {
>       cm.execCommand('delCharBefore');
>     }
>   },
>   'Shift-Tab': (cm) => cm.execCommand('indentLess')
> }
> ```

I love your solution

**Comment by MuhammadSawalhy** [comment]
There is a tiny problem with the code:

```diff
-        if (!(indentation !== 0 &&
+        if ((indentation !== 0 &&
           cursorPos.ch <= indentation &&
           cursorPos.ch % indentUnit === 0)) {
          shouldDelChar = true;
        }
```

**Comment by MuhammadSawalhy** [comment]
Your way of getting the indentation didn't work for me, `cm.getStateAfter(cursorPos.line).indented`, so I had to write a polyfill for it.

```js
// let indentation = cm.getStateAfter(cursorPos.line).indented;
let indentation = ((line) => {
  line = cm.doc.getLine(line);
  return line.match(/^\s+/)[0].length;
})(cursorPos.line);
```

**Comment by haacked** [comment]
The solution by @windy here works great, but [has one minor bug](https://github.com/codemirror/CodeMirror/issues/988#issuecomment-556928041).

If you indent the a blank line, then move the cursor to the beginning of the line and try to backspace, nothing happens. That's because in the conditional: 

```js
if (!(indentation !== 0 &&
   cursorPos.ch <= indentation &&
   cursorPos.ch % indentUnit === 0)) {
  shouldDelChar = true;
}
```

We don't meet the conditional because `indentation` is greater than 0 and `cursorPos.ch == 0` which means when you mod it against `indentUnit` it returns `0`.

We found several situations where backspace didn't work at the beginning of the line.

```js
if (!(indentation !== 0 &&
    cursorPos.ch > 0 &&
    cursorPos.ch <= indentation &&
    cursorPos.ch % indentUnit === 0)) {
    shouldDelChar = true;
}
```

Making this change seems to fix the issue. Note I added `cursorPos.ch > 0` to this conditional.
